//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityNotOtomasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNotlar
    {
        public int NotId { get; set; }
        public Nullable<int> Ogrenci { get; set; }
        public Nullable<int> Ders { get; set; }
        public Nullable<int> Sınav1 { get; set; }
        public Nullable<int> Sınav2 { get; set; }
        public Nullable<int> Sınav3 { get; set; }
        public Nullable<decimal> Ortalama { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual tblDersler tblDersler { get; set; }
        public virtual tblOgrenci tblOgrenci { get; set; }
    }
}
